In [21]:
import tensorflow as tf 
import transformers

In [22]:
import tensorflow as tf
new_model = tf.keras.models.load_model('sentiment_model',custom_objects={"TFBertModel": transformers.TFBertModel})

In [23]:
new_model.layers[2].trainable = False

In [24]:
new_model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 50)]         0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 50)]         0           []                               
                                                                                                  
 tf_bert_model (TFBertModel)    TFBaseModelOutputWi  108310272   ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 50,                                            

In [25]:
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained('bert-base-cased')

In [26]:
token = tokenizer.encode_plus("I love you sucker", 
                              add_special_tokens=True,
                              max_length=50, 
                              truncation=True,
                              padding="max_length",
                              return_token_type_ids=False,
                              return_attention_mask=True,
                              return_tensors='tf')

In [27]:
token

{'input_ids': <tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[  101,   146,  1567,  1128, 13054,  1200,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0]])>, 'attention_mask': <tf.Tensor: shape=(1, 50), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0]])>}

In [28]:
input_ids = token['input_ids']
attention_mask = token['attention_mask']

In [29]:
sentiment = new_model.predict([input_ids,attention_mask])[0]

1/1 [==============================] - 3s 3s/step


In [30]:
sentiment_labels = {0:'Anger', 
                    1:'Fear', 
                    2:'Joy',
                    3:'Love', 
                    4:'Sadness',
                    5:'surprise'}
sentiment = sentiment_labels[sentiment.argmax()]

In [31]:
print(f"Predicted sentiment:{sentiment}")

Predicted sentiment:Joy
